### ISSUE TITLE
DataModel.close() not working when file is opened with datamodels.open()

### ISSUE THREAD

**Issue by jdavies-st** [STScI-JWST/jwst#977] opened 2017-06-13 14:59 UTC
The `close()` method in `jwst.datamodels` is supposed to call the underlying `HDUList.close()` method and release file handles.  But it currently doesn't work when a FITS file is opened with `datamodels.open()`.

It turns out `close()` only works when you open a file with a specific datamodel, i.e.:
```
In [1]: from jwst import datamodels

In [2]: a = datamodels.ImageModel('jwst_file_cal.fits')

In [3]: a._files_to_close
Out[3]: [[<astropy.io.fits.hdu.image.PrimaryHDU object at 0x11d784860>, <astropy.io.fits.hdu.image.ImageHDU object at 0x11d788d68>, <astropy.io.fits.hdu.image.ImageHDU object at 0x11d7905c0>, <astropy.io.fits.hdu.image.ImageHDU object at 0x11d790ac8>, <astropy.io.fits.hdu.image.ImageHDU object at 0x11d790fd0>, <astropy.io.fits.hdu.image.ImageHDU object at 0x11d7954a8>]]

In [4]: a.close()

In [5]: a.close()
WARNING: AstropyDeprecationWarning: Accessing an HDU after an HDUList is closed, where
that HDU was no read while the HDUList was open
is deprecated.  That is, you did something like:

    >>> hdulist.close()
    >>> print(hdulist[2].header)

even though hdulist[2] had not been read yet.  Instead
do:

    >>> print(hdulist[2].header)
    >>> hdulist.close()

or open the file with lazy_load_hdus=False to read all
the HDUs into memory immediately upon opening the file.
 [astropy.io.fits.hdu.hdulist]
```
As we can, see when opened with a specific `DataModel`, the `_files_to_close` attribute gets populated.  `close()` then calls the the `close()` method on each `HDUList` contained in this attribute.

But when a file is opened by `datamodels.open`, the `_files_to_close` attribute does not get populated, and therefore when you try to close that datamodel, nothing happens.
```
In [6]: a = datamodels.open('nrca4_47Tuc_primary_dither2_newpos_cal.fits')

In [7]: a._files_to_close
Out[7]: []
```
This seems to happen because `open()` bypasses [a block](https://github.com/STScI-JWST/jwst/blob/master/jwst/datamodels/model_base.py#L152-L167) in `model_base.py` that populates `_files_to_close`.

**Comment by bernie-simon** [comment] 2017-06-13 17:36
I know what the issue is (thanks for the explanation), what caused it, and how to fix it. Datamodels.open() opens the file as an hdulist to get the number of dimensions, which it then uses to determine how to open the image. To save some time, it passes the hdulist to Datamodel(), so it doesn't need to open the file a second time. That's why your block is being bypassed.

**Comment by bernie-simon** [comment] 2017-08-03 13:59
Closing this issue, the bug has been fixed.

**Closed by bernie-simon** 2017-08-03 13:59 UTC
Labels: bug, datamodels
