### ISSUE TITLE
Task: NIRSpec wavecorr step

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#601] opened 2017-01-13 20:34 UTC
This is a continuation of Trac 373 https://aeon.stsci.edu/ssb/trac/jwst/ticket/373. A wavelength zeropoint correction needs to be implemented in calwebb_spec2, either as part of the initial assign_wcs process or as a separate step, that will correct wavelength assignments for sources not centered in a fixed slit or MSA slitlet.

Documentation is available at ​https://confluence.stsci.edu/download/attachments/61442267/ESA-JWST%E2%80%93SCI-NRS-TN-2016-003_wavelength_zero_point_1.pdf?version=1&modificationDate=1462212841000&api=v2

**Comment by nden** [comment] 2017-05-25 21:28
As I find out the details I'll document them here. 
The source x,y position in the shutter is given in the msa configuration file, columns `estimated_source_in_shutter_x` and `estimated_source_in_shutter_y`. These are read in by assign_wcs and saved in each `Slit` as `Slit.source_xpos` and `Slit.source_ypos`. The source position is in a coordinate system associated with each shutter whose origin is the upper left corner of the shutter. It looks like (unconfirmed yet) that positive x is to the right and positive y is downwards. To convert to the coordinate frame associated with the slit, where 0,0 is in the center of the slit, need to subtract -.05 in both directions.

**Comment by hbushouse** [comment] 2017-05-26 00:20
Don't subtract -.05, but rather subtract 0.5

**Comment by hbushouse** [comment] 2017-08-23 16:01
For fixed-slit exposures we don't have estimated source position in the slit being given to us from upstream, as is the case with MOS observations that have this information in the MSA metadata file. For fixed-slit exposures we will rely on the x/yoffset information for each exposure that is passed from PPS. It gives the relative offset of each exposure in a dither pattern relative to the center of the pattern, which for the fixed-slits is centered on the particular slit.

The exposure offsets will be recorded in the new header keywords XOFFSET and YOFFSET (see https://github.com/STScI-JWST/jwst/pull/1112). The keywords give offsets from the center of a slit in units of arcsec. Those values need to be transformed into fractional slit units for use in the wavelength zero-point correction, e.g. if the offset is -1.0 arcsec and the slit size is 1.5 arcsec, the fractional slit offset is -0.67.

**Comment by nden** [comment] 2017-08-25 19:06
@hbushouse In the example above, since (0,0) is the center of the slit, isn't the fractional offset -0.33?

**Comment by hbushouse** [comment] 2017-08-25 19:28
D'oh! You're right that I used the full slit size instead of the half-width, but in that case my example has an even more fatal flaw. If the full width of the slit is 1.5 arcsec, then the distance from (0,0) to either side is 0.75 arcsec and hence an offset of -1.0 arcsec is actually outside the left edge of the slit! So let's start over with a new example ...

Slit full-width is 1.5 arcsec, dither pattern offset is -0.5 arcsec, which means the fractional slit offset is -0.5/(1.5/2) = -0.67.

**Comment by nden** [comment] 2017-08-25 20:24
I am going to describe here what has been coded as a reference for the future:

`XOFFSET, YOFFSET` are the position of the target in x,y in the Ideal system. They correspond to `ideal_x_position` and `ideal_y_position` in the PPS database. (Not sure why they are called "offset").
The position (xoffset, yoffset) is transformed first to (V2, V3) coordinates and then to (Xmsa, Ymsa) coordinates. The slit (xcenter, ycenter) and (xsize, ysize) in the MSA frame are known.
The fractional `xpos_source` is computed as (Xmsa - xcenter) / (xsize/2).

**Comment by nden** [comment] 2017-09-13 22:38
Closed by #1091.

**Closed by nden** 2017-09-13 22:38 UTC
Labels: assign_wcs, NIRSPEC MSA, task
