### ISSUE TITLE
axis order in MIRI imager transforms may be switched

### ISSUE THREAD

**Issue by nden** [STScI-JWST/jwst#164] opened 2016-08-16 17:42 UTC
```
im.meta.wcs.get_transform('detector', 'focal')( 900. ,700)
Out[7]: (-1.9431383255402122, -7.91479684787932)
```
Judging by the values these are probably switched. Need to verify and fix this.

**Comment by brechmos-stsci** [comment] 2016-10-19 15:09
Confirmed that it appears to be a problem.

The file `MIRI-TN-00070-ATC_Imager_distortion_CDP_Iss5.pdf` contains a table on page 5 that has V2/V3 and MIRI SCA pixels.  

To create the data file I took the `jw93065001002_02105_00001_mirimage_rate.fits`, modified the header field `NUMDTHPT` to be a string '0' rather than an integer 0 (as the schema appears to want a string), and I added in the refs:
```
In [16]: f[0].header['V2_REF'] = -453.5134
In [21]: f[0].header['V3_REF'] = -72.0545718428
In [18]: f[0].header['RA_REF'] = 5.6
In [19]: f[0].header['DEC_REF'] = -13.5
In [20]: f[0].header['ROLL_REF'] = 337.125305
```
based on comments from Nadia.

I ran the assign_wcs and read in the resulting WCS transform.  
```
In [27]: from jwst.datamodels import ImageModel
In [28]: a = ImageModel('jw93065001002_02105_00001_mirimage_rate_assign_wcs.fits')
In [31]: a.meta.wcs
In [35]: tt = a.meta.wcs.get_transform('detector', 'v2v3')
In [36]: tt(900., 700.)
Out[36]: (-1.9431383255402122, -7.91479684787932)
```
On page 5 of the PDF file, it does say the v2 should be -8.0 and the V3 should be -2.0.  So, it does appear that the outputs are swapped.

**Comment by brechmos-stsci** [comment] 2016-10-19 17:35
I looked at just the distortion file itself and it seems to be the source of the problem:

```
In [50]: a = AsdfFile.open('/grp/crds/cache/references/jwst/jwst_miri_distortion_0007.asdf')

In [51]: a.tree['model']
Out[51]: <CompoundModel54(c0_0=-12.774999618530273, c1_0=0.02499999850988388, c0_1=-12.774999618530273, c1_1=0.02500000037252903, c0_0_3=0.0002779261558316648, c1_0_3=1.385405812470708e-05, c2_0_3=-0.0008357166079804301, c3_0_3=-1.0612609457893996e-07, c4_0_3=4.864141942562128e-07, c0_1_3=2.8437325954437256, c0_2_3=0.00011153987725265324, c0_3_3=-0.00011824401735793799, c0_4_3=3.311309228593018e-06, c1_1_3=-1.815903488022741e-05, c1_2_3=1.067891275852162e-06, c1_3_3=-2.590377050637471e-07, c2_1_3=-6.579341425094754e-05, c2_2_3=3.2994903449434787e-06, c3_1_3=1.7919234096552827e-07, c0_0_4=6.470080734288786e-06, c1_0_4=2.822078227996826, c2_0_4=-2.873002813430503e-05, c3_0_4=2.439489207972656e-06, c4_0_4=1.5976526412941894e-07, c0_1_4=-0.00020063390547875315, c0_2_4=2.4326425773324445e-05, c0_3_4=2.189153519793763e-06, c0_4_4=-2.4686968913556484e-07, c1_1_4=-0.0016774788964539766, c1_2_4=-3.3127689675893635e-05, c1_3_4=2.2623519271292025e-06, c2_1_4=1.9835767943732208e-06, c2_2_4=-1.9065278422658594e-07, c3_1_4=1.81334576154768e-06, c0_0_6=-1.5400006771087646, c1_0_6=-0.026083583012223244, c0_1_6=-0.0020299148745834827, c0_0_7=-7.228002071380615, c1_0_7=0.0020299144089221954, c0_1_7=-0.026083586737513542)>

In [53]: a.tree['model'](945,728)
Out[53]: (-2.0008591851076445, -7.99326608345772)
```
So, after talking to @nden I decided that I should just change the script that creates the distortion file.

**Comment by brechmos-stsci** [comment] 2016-10-20 13:18
This ticket is fixed primarily by https://github.com/spacetelescope/jwreftools/pull/13 and then a small bit of code cleanup and fixing were done in #365 .  So once those two are merged then this ticket can be closed.

**Closed** 2016-10-20 14:26 UTC
Labels: assign_wcs, MIRI IMAGER
