### ISSUE TITLE
Update grism source catalog column names in extract_2d

### ISSUE THREAD

**Issue by hbushouse** [STScI-JWST/jwst#1653] opened 2018-01-10 19:05 UTC
Alicia Canipe (INS) reported the following error when running calwebb_spec2 on a grism exposure:
```
KeyError: "Missing required columns in source catalog (V54321001002P000000000110d_A5_F444W_cat.ecsv): {'sky_centroid', 'semiminor_axis_sigma', 'source_sum', 'area', 'source_sum_err', 'orientation_sky', 'semimajor_axis_sigma', 'orientation'}"
```
(see Basecamp message thread https://stsci-ins.basecamphq.com/projects/11477312-jwst-pipeline/posts/104268056/comments).

@sosey indicates that this is due to the fact that some of the column names have been changed in the source_catalog step and hence portions of extract_2d need to be updated to use the new column names.

**Comment by sosey** [comment] 2018-01-10 19:06
closing - duplicate of #1602

**Closed by sosey** 2018-01-10 19:06 UTC
Labels: Wide Field Slitless Spec (WFSS), extract_2d
